### ISSUE TITLE
Support multiple config paths

### ISSUE THREAD

**Issue by ybiquitous** [eddsteel/bump-orb#3]
Currently, the `config` input parameter supports only one file path (default: `.circleci/config.yml`) like this:

```yaml
- uses: eddsteel/bump-orb@v1
  with:
    config: .circleci/config_foo.yml
```

But I believe it'd be so helpful if we could specify multiple config paths as below (e.g., space-separated):

```yaml
- uses: eddsteel/bump-orb@v1
  with:
    config: |
      .circleci/config.yml
      .circleci/config_foo.yml
      .circleci/config_bar.yml
```

Or, the file pattern support might be more helpful:

```yaml
- uses: eddsteel/bump-orb@v1
  with:
    config: .circleci/*.yml
```

I'd appreciate it if you could consider providing such a feature. Thank you. 😃
